version: "3.7"
services:
    db:
        build: ./db
        container_name: db
        ports:
          - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL _ROOT_PASSWORD: T0day.T1jan333
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: T0day.T1jan333
        networks:
            website_network:
                aliases:
                    - wordpress
    wordpress:
        build: .
        container_name: wordpress
        ports:
            - "80:80"
        networks:
            website_network:
                aliases:
                    - wordpress
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_PASSWORD: T0day.T1jan333
            WORDPRESS_DB_NAME: wordpress
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - "80:80"
        networks:
            website_network:
                aliases:
                    - nginx-proxy           
networks:
    website_network:
        name: website_network
volumes:
    db_data:
        driver: local
        name: MYSQL_DATABASE

    cloudflare-ddns:
        container_name: cloudflareDNS
        image: oznu/cloudflare-ddns
        restart: always
        environment:
          PUID: 0
          PGID: 0
        API_KEY: ktez6xlMnDf0yaD5xGuUjgI-PV95A2Dn3tohz6wV
        ZONE: starsgrooming.co.uk
    
    watchtower:
      image: containrrr/watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment: 
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_LABEL_ENABLE=true
        - WATCHTOWER_INCLUDE_STOPPED=true
        - WATCHTOWER_REVIVE_STOPPED=true
        - WATCHTOWER_POLL_INTERVAL=604800